# Generated by Django 5.0.4 on 2024-04-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
