repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash run_mypy.sh
        language: system
        types: [ python ]
        pass_filenames: false
        args: [ ".", "--config-file=pyproject.toml", "--skip-cache-mtime-checks", "--cache-fine-grained" ]