# Generated by Django 5.0.4 on 2024-04-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('subscribed_at', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.schools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
            options={
                'db_table': 'subscriptions',
                'unique_together': {('user_id', 'school_id')},
            },
        ),
    ]
