# Generated by Django 5.0.4 on 2024-04-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="publisher",
                        to="users.users",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subscriber",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.AddConstraint(
            model_name="subscriptions",
            constraint=models.UniqueConstraint(
                fields=("publisher_id", "subscriber_id"), name="unique_user_publisher"
            ),
        ),
    ]
