# Generated by Django 5.0.4 on 2024-04-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='district',
            new_name='district_name',
        ),
    ]
