# Generated by Django 5.0.4 on 2024-04-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='city',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
