# Generated by Django 5.0.4 on 2024-04-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_district_name_schools_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schools',
            unique_together={('name', 'city')},
        ),
    ]
