# Generated by Django 5.0.4 on 2024-04-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_schools_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'db_table': 'school_news',
            },
        ),
    ]
