# Generated by Django 5.0.4 on 2024-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
