# Generated by Django 5.0.4 on 2024-04-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_schoolnews_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnews',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.schools'),
        ),
    ]
